apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grid-api.fullname" . }}
  labels:
{{ include "grid-api.labels" . | indent 4 }}
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key | quote }}: {{ $value | b64enc }}
  {{- end }}
